### ISSUE TITLE
[git] Missing images on slides

### ISSUE THREAD

**Issue by SpongeJr** [gdisf/teaching-materials#143]
The following images from the slides are 404 now. I found what may have been the images that were there (don't know for sure), but I didn't want to make those changes and send a PR as I don't know the whole story as to the rights or if these other sites mind the links, or what to do?

Missing: http://thkoch2001.github.com/whygitisbetter/images/local-remote.png 
Possible replacement: https://github.com/schacon/whygitisbetter/blob/master/images/local-remote.png

Missing: http://www.sitepoint.com/wp-content/uploads/2010/10/branching.jpg
Possible replacement: http://dab1nmslvvntp.cloudfront.net/wp-content/uploads/2010/10/branching.jpg

Missing: https://a248.e.akamai.net/assets.github.com/images/modules/about_page/octocat.png?1306884374
Possible replacement: Is there a particular octocat that should be here?

**Comment by pamelafox** [comment]
I don't think I was particularly good about citing attributions when I made those slides, and I haven't taught from those slides in a while. Those changes all look good, and you could add an attribution on the slide. Or you could re-draw the diagrams in a program like MyBalsamiq/Gliffy.
