### ISSUE TITLE
[ajax] Add README.md material

### ISSUE THREAD

**Issue by brendajin** [gdisf/teaching-materials#150]
Add Meetup description and follow up email

**Comment by pamelafox** [comment]
Isn't it here? https://github.com/pamelafox/teaching-materials/blob/master/ajax/README.md

Or do you mean add more to it, like the follow-up email? I haven't ported those over yet, I could.

**Comment by brendajin** [comment]
@pamelafox thx for the description! yep I mean the follow up email
