### ISSUE TITLE
JS401Intro to Unit Testing with Jasmine

### ISSUE THREAD

**Issue by inclusiveThinking** [gdisf/teaching-materials#174]
http://www.teaching-materials.org/jasmine/step0/instructions.html
Considering adding comments in GameSpec.js and Game.js so files are not empty. Consider explaining relationships to App.js and index.html

http://www.teaching-materials.org/jasmine/#/15
Considering explaining or defining "suites" and "specs" and the difference between the two (based on student question)

http://www.teaching-materials.org/jasmine/#/24
Consider providing a definition for "stubbing" (based on student question)

**Comment by verythorough** [comment]
It looks like this issue has been solved with your commit back in March?
