### ISSUE TITLE
[Algorithms] Improvements

### ISSUE THREAD

**Issue by pamelafox** [gdisf/teaching-materials#177]
- [x] Lesson plan: Print out sorting instructions, print out mazes, make decks of 1-12
- [x] Add diagram of graphs in the Time Complexity chart, to compare them all. 
- [x] Add to quick sort instruction info on picking a pivot.
- [ ] Fix k-means clustering size.
- [ ] Move DFS exercise closer to explanation.
- [ ] Perhaps clarify graph traversal vs. graph search
- [ ] Flesh out "more graph search slide" - better visual for simulated annealing. Or just don't explain?
- [ ] Link to Spatial Prepositions research from decision tree slide

**Comment by brendajin** [comment]
@adowns01 can you give us an update on the list of issues? I think the graph ones are no longer relevant... is that correct?

**Comment by adowns01** [comment]
I don't think any of these are relevant anymore, but I'm sure we'll have plenty of new ones after tomorrow!
