### ISSUE TITLE
[html/css] make a dummy website and use it throughout the exercises as an example

### ISSUE THREAD

**Issue by brendajin** [gdisf/teaching-materials#189]
select a single full website and use that for examples throughout the workshop

**Comment by verythorough** [comment]
I agree! I think we might be able to integrate the exercises from the old HTML/CSS curriculum (like [this example](http://www.teaching-materials.org/htmlcss-1day/html-basics/exercise_descrip.html)) to give a more focused progression that parallels the typical exercise progression in most of the other workshops.

**Comment by pamelafox** [comment]
FYI, there is a sample-code folder in the new slides that has webpages you can use throughout. It is one webpage for class, which worked out well for me.
