### ISSUE TITLE
[JS101] broken image link

### ISSUE THREAD

**Issue by cdersky** [gdisf/teaching-materials#194]
On slide 2 (found here: http://www.teaching-materials.org/javascript/slides/programming.html) the image link is broken The speaker notes do not indicate what the image was, hence I am not sure what to replace it with.

**Comment by trucnguyen** [comment]
Original source was http://panther.110mb.com/3d-game-writing/pictures/dumb_computer3.gif

**Comment by FrenchBen** [comment]
As an alternative, I made this gif

![Black Books Fran](https://cloud.githubusercontent.com/assets/3965324/13901244/485cc144-edda-11e5-8d9d-5549778796dd.gif)
