### ISSUE TITLE
JS- Exercise-Variables Future Teller solution Developer Env Error

### ISSUE THREAD

**Issue by chatasweetie** [gdisf/teaching-materials#196]
The Future Teller solution has a variable name 'location' which in the developer tool console will error out - this confused many students. I recommend changing the variable name to 'place'

**File**
`/javascript/exercises/variables.html`

**Comment by brendajin** [comment]
Fixed with [1b1e23a181a35e595508647ab7121f2e5003ccf7](https://github.com/gdisf/teaching-materials/commit/1b1e23a181a35e595508647ab7121f2e5003ccf7)
