### ISSUE TITLE
[css3] Exercise files missing

### ISSUE THREAD

**Issue by brendajin** [gdisf/teaching-materials#197]
There are three exercise files from the `css3/` directory that are missing:

```
exercise_less.html
exercise_tables.html
exercise_logo.html
```

I haven't been able to find these through a history of the `css3/` directory

**Comment by brendajin** [comment]
[This is the first commit of that directory](https://github.com/gdisf/teaching-materials/commit/ff94c87aca86aa785c1f7795a24c1e56ae87a881)

@pamelafox any idea where the other files are? I've grepped through the history for those names but don't see them moved from another location.

**Comment by pamelafox** [comment]
A-ha, found them!
https://dl.dropboxusercontent.com/u/10998095/css3-workshop/exercise_tables.html
https://dl.dropboxusercontent.com/u/10998095/css3-workshop/exercise_logo.html
https://dl.dropboxusercontent.com/u/10998095/css3-workshop/exercise_less.html

**Comment by transitorytammy** [comment]
https://github.com/gdisf/teaching-materials/pull/202
