### ISSUE TITLE
[JSMVC] Improvements and notes

### ISSUE THREAD

**Issue by pamelafox** [gdisf/teaching-materials#20]
- Slide on how to turn spaghetti code into MVC (like in Addy's digesting MVC slides)
- Change MVC exercise to create VideoListView, with bonus of creating an ItemView nested inside. (Can't do this unless we change the HTML to not be a UL, List would need to create the ul)

**Comment by brendajin** [comment]
Which slide in particular from [the deck](http://addyosmani.com/blog/digesting-javascript-mvc-pattern-abuse-or-evolution/) are you referring to @pamelafox ?

**Comment by pamelafox** [comment]
Found it:
<img width="558" alt="screen shot 2015-08-06 at 7 58 57 pm" src="https://cloud.githubusercontent.com/assets/297042/9127855/a05ceb2e-3c75-11e5-916d-5eb1d1b476e7.png">

We kind of talk about it, but I wonder if it'd help to show an example of turning spaghetti code into MVC, one that is similar but also different enough from their exercise.
