### ISSUE TITLE
[HTML/CSS] Additional readability resource

### ISSUE THREAD

**Issue by pamelafox** [gdisf/teaching-materials#21]
http://coding.smashingmagazine.com/2013/02/19/using-white-space-for-readability-in-html-and-css/

**Comment by trucnguyen** [comment]
The link already exists but redirects to another page presumably because Smashing's CMS changed.

We should update the link directly to redirect URL: https://www.smashingmagazine.com/2013/02/using-white-space-for-readability-in-html-and-css/

**Comment by brendajin** [comment]
@trucnguyen can you specify where this link should go?

**Comment by trucnguyen** [comment]
@brendajin We should update the link directly to here: https://www.smashingmagazine.com/2013/02/using-white-space-for-readability-in-html-and-css/

**Comment by brendajin** [comment]
The updated link should go here: `htmlcss-1day/html-basics/slides.html`

**Comment by MistyReed** [comment]
Link update already completed.
