### ISSUE TITLE
[htmlcss-1day] Convert slides to reveal.js

### ISSUE THREAD

**Issue by brendajin** [gdisf/teaching-materials#235]
Convert the slides from fathom.js to reveal.js in the `htmlcss-1day/` directory
# Instructions
- [ ] Use `example/index.html` as a template
- [ ] Add Creative Commons license footer.  See below for snippet.
- [ ] There may be multiple slide decks. Please look at each `*.html` file
- [ ] Use `reveal.js`,  `gdilight` theme from `common/` directory
- [ ] All libs must be from the `common/` directory, including jQuery, Bootstrap, etc
- [ ] Update exercise instructions to also include `common/` directory libs
- [ ] Change all remote images to local inside `htmlcss-1day/images/` directory
- [ ] Delete subfolder libraries
- [ ] All slides need to be horizontal
- [ ] Do not include content changes
## Testing
- [ ] Check and make sure the slides look correct on your computer
- [ ] Check that footer includes Creative Commons license image and link
## Footer Snippet

```
<footer>
  <div class="copyright">
  Official class name here -- Chapter name here (if content modified from original) --
  <a rel="license" href="../common/http://creativecommons.org/licenses/by-nc/3.0/deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc/3.0/80x15.png" /></a>
  </div>
</footer>
```

**Comment by pamelafox** [comment]
Since the new slides use reveal.js, I think this issue could be closed?

**Comment by trucnguyen** [comment]
@pamelafox Yep the 2 day slides do but,
did we want to keep these around and convert them? https://www.teaching-materials.org/htmlcss-1day/ ?

**Comment by pamelafox** [comment]
I would keep around the slides as URLs are forever, and that URL has been passed around a lot. However, if you don't want to confuse people who visit the front page, you could remove it from the index.

As for porting to reveal, it doesn't seem worth the effort if they will not be taught by GDI in future. Personally, I don't actually like the reveal.js template, I find it hard to visibly parse and the CSS harder to customize. I would only go through the effort of using it when the goal is consistency in current GDI workshops, and when real effort can be put into the slide readability.

Those are my 2 cents; other opinions are welcome!
