### ISSUE TITLE
[ajax] Convert slides to reveal.js

### ISSUE THREAD

**Issue by brendajin** [gdisf/teaching-materials#238]
Convert the slides from fathom.js to reveal.js in the `ajax/` directory
# Instructions
- [x] Use `example/index.html` as a template
- [x] Add Creative Commons license footer.  See below for snippet.
- [x] There may be multiple slide decks. Please look at each `*.html` file
- [x] Use `reveal.js`,  `gdilight` theme from `common/` directory
- [x] All libs must be from the `common/` directory, including jQuery, Bootstrap, etc
- [x] Update exercise instructions to also include `common/` directory libs
- [x] Change all remote images to local inside `ajax/images/` directory
- [x] Delete subfolder libraries
- [x] All slides need to be horizontal
- [x] Do not include content changes
## Testing
- [x] Check and make sure the slides look correct on your computer
- [x] Check that footer includes Creative Commons license image and link
## Footer Snippet

```
<footer>
  <div class="copyright">
  Official class name here -- Chapter name here (if content modified from original) --
  <a rel="license" href="../common/http://creativecommons.org/licenses/by-nc/3.0/deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc/3.0/80x15.png" /></a>
  </div>
</footer>
```

**Comment by selva-oscura** [comment]
Changes made and pushed to own repo and pull request sent.

**Comment by a-staab** [comment]
@a-staab I'll take this!

**Comment by a-staab** [comment]
Actually, this is already done! :)
