### ISSUE TITLE
[jQuery] Convert slides to reveal.js

### ISSUE THREAD

**Issue by verythorough** [gdisf/teaching-materials#239]
Convert the slides from fathom.js to reveal.js in the `jquery/` directory

# Instructions
- [ ] Use `example/index.html` as a template
- [ ] Add Creative Commons license footer.  See below for snippet.
- [ ] There may be multiple slide decks. Please look at each `*.html` file
- [ ] Use `reveal.js`,  `gdilight` theme from `common/` directory
- [ ] All libs must be from the `common/` directory, including jQuery, Bootstrap, etc
- [ ] Update exercise instructions to also include `common/` directory libs
- [ ] Change all remote images to local inside `jquery/images/` directory
- [ ] Delete subfolder libraries
- [ ] All slides need to be horizontal
- [ ] Do not include content changes

## Testing
- [ ] Check and make sure the slides look correct on your computer
- [ ] Check that footer includes Creative Commons license image and link

## Footer Snippet
```
<footer>
  <div class="copyright">
  Official class name here -- Chapter name here (if content modified from original) --
  <a rel="license" href="../common/http://creativecommons.org/licenses/by-nc/3.0/deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc/3.0/80x15.png" /></a>
  </div>
</footer>
```

**Comment by selva-oscura** [comment]
Working on this.....
