### ISSUE TITLE
[JS 101] Remove ages from exercises

### ISSUE THREAD

**Issue by pamelafox** [gdisf/teaching-materials#24]
From our feedback form:
"GDI is an organization whose reason for existence is to fight stereotype threat. I partnered with a woman who was older the first day, and I think the fact that the exercises asked for our ages activated stereotype threat. She didn't show up the next day."

I don't know if that's the case or not, but it woudn't hurt to change the exercises. The "age calculator" and "about me" exercises both end up asking for age.

cc @icyfenix

**Comment by brendajin** [comment]
Here are the age calculators:
`javascript/exercises/functions.html`
`javascript/exercises/variables.html`

Haven't found the "about me" one yet
