### ISSUE TITLE
[jsmvc] Convert slides to GDI theme and use common libraries

### ISSUE THREAD

**Issue by brendajin** [gdisf/teaching-materials#240]
Convert the slides to `gdilight` theme in the `jsmvc/` directory
# Instructions
- [ ] Use `reveal.js`,  `gdilight` theme from `common/` directory
- [ ] All libs must be from the `common/` directory, including jQuery, Bootstrap, etc
- [ ] Update exercise instructions to also include `common/` directory libs
- [ ] Change all remote images to local inside `jsmvc/images/` directory
- [ ] Delete subfolder libraries
- [ ] Do not include content changes
## Testing
- [ ] Check and make sure the slides look correct on your computer

**Comment by FrenchBen** [comment]
@m-brian is working on this.

**Comment by trucnguyen** [comment]
Resolved in this PR: https://github.com/gdisf/teaching-materials/pull/390
