### ISSUE TITLE
[jquery2] Convert slides to reveal.js

### ISSUE THREAD

**Issue by verythorough** [gdisf/teaching-materials#244]
Convert the slides from fathom.js to reveal.js in the `jquery2/` directory

# Instructions
- [ ] Use `example/index.html` as a template
- [ ] Add Creative Commons license footer.  See below for snippet.
- [ ] There may be multiple slide decks. Please look at each `*.html` file
- [ ] Use `reveal.js`,  `gdilight` theme from `common/` directory
- [ ] All libs must be from the `common/` directory, including jQuery, Bootstrap, etc
- [ ] Update exercise instructions to also include `common/` directory libs
- [ ] Change all remote images to local inside `jquery2/images/` directory
- [ ] Delete subfolder libraries
- [ ] All slides need to be horizontal
- [ ] Do not include content changes

## Testing
- [ ] Check and make sure the slides look correct on your computer
- [ ] Check that footer includes Creative Commons license image and link

## Footer Snippet
```
<footer>
  <div class="copyright">
  Official class name here -- Chapter name here (if content modified from original) --
  <a rel="license" href="../common/http://creativecommons.org/licenses/by-nc/3.0/deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc/3.0/80x15.png" /></a>
  </div>
</footer>
```

**Comment by tgaff** [comment]
@verythorough I have the slides converted over to reveal.js, but have a question.  Is the footer needed on all slides?  Or just first and maybe last?

**Comment by verythorough** [comment]
@tgaff Sorry I didn't see this sooner!  Too many in-person questions. :)

With reveal, you only need to include the footer once in `index.html`, and it will show up on all slides.  To see a working example, you can look at lines 434-438 in  `jasmine/index.html` (shortcut [here](https://github.com/gdisf/teaching-materials/blob/master/jasmine/index.html#L434)).  Those 5 lines make it so that the footer shows on all of the slides, like [this](http://www.teaching-materials.org/jasmine/#/).

You'll do the same thing as that in `jquery/index.html`.
