### ISSUE TITLE
[d3] Use ../common/ library plugins for reveal

### ISSUE THREAD

**Issue by brendajin** [gdisf/teaching-materials#245]
Convert the slides to `gdilight` theme in the `../common/` directory

For the final conversion to reveal, in the Reveal.initialize call, make sure plugin dependencies refer to ../common/

# Instructions
- [x] Use `reveal.js`,  `gdilight` theme from `common/` directory
- [x] All libs must be from the `common/` directory, including jQuery, Bootstrap, etc
- [x] Update exercise instructions to also include `common/` directory libs
- [x] Change all remote images to local inside `javascript/images/` directory
- [x] Delete subfolder libraries
- [x] Do not include content changes
## Testing
- [ ] Check and make sure the slides look correct on Netlify preview

**Comment by trucnguyen** [comment]
Exercises live on jsfiddle, should we consider moving them to local? It's outside the scope for this issue so I'd log another.

For the final conversion to reveal, in the Reveal.initialize call, make sure plugin dependencies refer to ../common/
