### ISSUE TITLE
[jsoo] Convert slides to GDI theme and use common libraries

### ISSUE THREAD

**Issue by brendajin** [gdisf/teaching-materials#246]
Convert the slides to `gdilight` theme in the `jsoo/` directory
# Instructions
- [ ] Use `reveal.js`,  `gdilight` theme from `common/` directory
- [ ] All libs must be from the `common/` directory, including jQuery, Bootstrap, etc
- [ ] Update exercise instructions to also include `common/` directory libs
- [ ] Change all remote images to local inside `jsoo/images/` directory
- [ ] Delete subfolder libraries
- [ ] Do not include content changes
## Testing
- [ ] Check and make sure the slides look correct on your computer

**Comment by FrenchBen** [comment]
@m-brian is working on this.

**Comment by selva-oscura** [comment]
I'll be working on this.
Since the students won't be downloading the whole repo, should the exercises pull bootstrap and jquery from the cdns rather than from the common directory?

**Comment by verythorough** [comment]
All of the exercises use repl.it, and don't require downloading any files, so the only bootstrap links are in the exercise instructions, which are fine as-is.

As a separate issue, repl.it now requires a login, and may not be the best choice for these exercises anymore.  I'm planning to use codepen instead for the lesson I'm teaching this week.
