### ISSUE TITLE
[apis] fix links

### ISSUE THREAD

**Issue by brendajin** [gdisf/teaching-materials#247]
The APIs content actually lives under `teaching-materials`, but is currently linking to another appspot app. Please change all these links from `http://gdisf-js-apis.appspot.com/` to the correct Github Pages ones for `teaching-materials.org` 

**Files**
`/index.html`
`http://www.teaching-materials.org/apis/`

**Comment by snajmi** [comment]
Working on it!

**Comment by snajmi** [comment]
Fixed and submitted pull request

**Comment by AlphaZach** [comment]
All I did is for the issue #247
