### ISSUE TITLE
[css3] missing files

### ISSUE THREAD

**Issue by brendajin** [gdisf/teaching-materials#248]
The following files are missing from the CSS3 directory:

```
css3/files/00_basic.html
css3/files/01_attr.html
css3/files/05_nth.html
css3/files/05_flag.html
css3/files/06_not.html
css3/files/08_dropcap.html
css3/exercise_tables_before.html
css3/exercise_less_before.html
```

**Comment by brendajin** [comment]
@pamelafox any idea where these are?

**Comment by pamelafox** [comment]
Found them in my Dropbox, CSS3 used to be served off there. Attaching:

[files.zip](https://github.com/gdisf/teaching-materials/files/359879/files.zip)
[exercise_before.zip](https://github.com/gdisf/teaching-materials/files/359884/exercise_before.zip)

**Comment by brendajin** [comment]
Instructions:

Please add these files under the appropriate `css3/` subdirectories

**Comment by snajmi** [comment]
Working on it!

**Comment by snajmi** [comment]
Fixed and submitted pull request.

**Comment by pamelafox** [comment]
The files originally referenced in this issue are there now, for CSS3.
