### ISSUE TITLE
[JS 101] Slow down the second day of lessons

### ISSUE THREAD

**Issue by pamelafox** [gdisf/teaching-materials#25]
We've had feedback from multiple students that the second day is too fast (even those already familiar with programming). We could slow it down and remove somethings (we could remove Animation and Events entirely, perhaps, and do more DOM exercises). We could break the DOM section up more.

cc @icyfenix

**Comment by brendajin** [comment]
We have restructured the curriculum to be run as follows:

1. Intro to HTML
2. Arrays, Objects, Functions
3. JS and the Web
