### ISSUE TITLE
[javascript] Add Object.keys() exercise

### ISSUE THREAD

**Issue by brendajin** [gdisf/teaching-materials#251]
Add an exercise after the `Object.keys()` lesson that asks the students to do the following

There is an array of animals at the zoo
`["zebra", "giraffe", "elephant", "snake", "zebra", "elephant", "snake", "panda"]`

Using `Object.keys()` count the number of unique animals at the zoo
## Testing
- [ ] copy the format of other exercises and provide a clickable solution
- [ ] test your solution and make sure it works
- [ ] exercise should live under the `javascript/exercises/` directory
- [ ] exercise should be linked from an HTML slide in the `javascript/` directory
- [ ] exercise should be linked from `javascript/index.html`

**Comment by tlhunter** [comment]
We may want to use an object instead of an array to represent the animals, something like this:

```js
var animals = {
  "zebra": "black and white",
  "giraffe": "brown"
};
console.log(Object.keys(animals)); // 2
```

Otherwise, if it were an array, one could simply `animals.length`.
