### ISSUE TITLE
[javascript] Broken Currency Converter link in javascript index

### ISSUE THREAD

**Issue by TrevorArcher** [gdisf/teaching-materials#254]
In the javascript table of contents for Lesson 2, there is a homework link for "The Currency Converter" `/javascript/exercises/currencyConverter.html` that leads to a 404. 

I found that `currencyConverter.html` seemed to be replaced with `cashRegister.html` in commit `459cd14`. However, since the Cash Register exercise utilizes objects, it would be better suited for Lesson 3.

**Comment by ayaseit** [comment]
I'll take it

**Comment by ayaseit** [comment]
Checked the main repository, looks like my commit to fix the #254 is already merged to it. 👍

**Comment by verythorough** [comment]
Fixed with #285
