### ISSUE TITLE
[jquery] Add exercise

### ISSUE THREAD

**Issue by brendajin** [gdisf/teaching-materials#257]
# Summary

Add 2 exercises to the `jquery/` directory: https://github.com/esthersweon/gdi-credit-card 
- [ ] Where the exercises should go in the sequence of slides is reflected [here](https://docs.google.com/presentation/d/1ITkmeNdWG1hBxMz5eRO-_lpDblw7scyWMivw-9SCfBU/edit#slide=id.g15da571cb7_1_0)
- [ ] Make sure all links in the slide deck work properly before submitting
- [ ] Make sure there is an `index.html` file to each exercise that summarizes instructions for students
- [ ] The instructions for students should link them to a `*.zip` of the starter kit, or in the case of the second exercise should also encourage students to use their work from the previous exercise

**Comment by colleenboodleman** [comment]
working on issue #257 jquery/

**Comment by sarahec** [comment]
I'm also working on it w/ colleen

**Comment by sarahec** [comment]
The existing exercise 3 (videoplayer_jquery.html) exercises the same set of skills as the new convert-to-jquery, namely taking existing DOM code and converting it to jquery.

My feeling is we leave the existing exercise in place, not add convert-to-jquery, and add the animation exercise (with alterations so it builds on the video player.) This will also require adding a slide or two on jQuery animation.

@brendajin does this make sense to you?

**Comment by brendajin** [comment]
@sarahec which advanced exercise do you want to add? is that the advanced fade one in the other repository?

A little bit of context here is that students asked for projects they could build upon and keep working on after the workshops. This workshop is also taught after Intro to HTML/CSS and Intro to JavaScript. In Intro to HTML/CSS students make a static About Me page. In Intro to JavaScript, they make a credit card validator with no UI. That's why there's some new UI exercises in the `gdi-credit-card` instead of the older Video Editor.

I agree that it sounds like the same skills are being exercised, and it doesn't make sense to have both.

How would you feel about adding the slides without the exercises... then we can figure out how to make the exercises work later?

**Comment by verythorough** [comment]
I haven't tried the credit card validator exercises yet, but I will say that I hesitate to remove the video-watcher exercise, because it's revisited in jQuery2, AJAX, APIs, JSMVC, and to lesser degree, JSOO.  It's been a useful project in my class up through jQuery2, and I plan to continue with it in the next lessons.  Perhaps just put both exercises on the same page like earlier JS exercises?

Regarding having slides about jQuery animations, those are covered (briefly) in jQuery2. If the two modules are merged as described in #256, it may make more sense to put the animation exercise after those.

**Comment by sarahec** [comment]
It sounds like the animation exercises should be pushed to jquery2. That leaves the question of whether to do the credit card validator or video watcher (or both perhaps.)

One thought is to start with the UI-less CC validator and build its UI from scratch *with jQuery*, replacing exercise 1. Then modify exercise 3 (the video player) to be a convert-DOM-code-to-jQuery exercise, preserving its use in later modules.

I had considered adding the CC example as an option alongside the video player (or vise versa), but that can confuse students.

Thoughts? It sounds like whatever change we make has to account for other labs that occur both before and after this module.
