### ISSUE TITLE
[admin] GirlDevelopIt should be Girl Develop It

### ISSUE THREAD

**Issue by brendajin** [gdisf/teaching-materials#258]
# Summary

- [ ] Replace all copy instances of `GirlDevelopIt` with `Girl Develop It`. 
- [ ] Make sure not to replace any URLs

## Example
In `teaching-materials/jquery/exercises/domaccess.html`:

```
<li>The logos of the media sources that featured GirlDevelopIt (lifeHacker, TED, etc., at the bottom of the page)</li>
```

Should be
```
<li>The logos of the media sources that featured Girl Develop It (lifeHacker, TED, etc., at the bottom of the page)</li>
```

**Comment by KangboLu** [comment]
I found three typos in three files and the pull request is made.
