### ISSUE TITLE
Algorithms Front Page needs Discoverablility Hint for using Arrow keys or Uses Old Review.js

### ISSUE THREAD

**Issue by nowucca** [gdisf/teaching-materials#273]
Browse to http://www.teaching-materials.org/algorithms/

There is no indication that one should use the arrow keys for navigating.

We should either add that as a note or (better) check to see if we can update the review.js to a newer version that adds the discoverability hint for us.

**Comment by nowucca** [comment]
Fixing by adding an indicator to discover how to advance - it's beyond scope of a hackathon to convert the <section>-based algorithms section to a <div class="slide normal"> regime.

**Comment by trucnguyen** [comment]
Thanks for taking a stab. The slides were converted to use a properly formatted reveal theme so the arrow affordance is more visible.
