### ISSUE TITLE
/htmlcss/lesson2/exercise_solution.html broken links

### ISSUE THREAD

**Issue by victorwltsang** [gdisf/teaching-materials#288]
/htmlcss/lesson2/exercise_solution.html

drumbeat don't exist 

links dont go anywhere

**Comment by KangboLu** [comment]
![drumbeat](https://cloud.githubusercontent.com/assets/17485959/17268040/2c4f026e-55d1-11e6-8dc5-e6978e324cdf.jpg)
The website's resources are no longer exist.
