### ISSUE TITLE
I cannot see Interview Preparation Material on the site

### ISSUE THREAD

**Issue by nowucca** [gdisf/teaching-materials#300]
I'm at the SFHTML5 meetup and I have not seen any interview preparation material on the website.

I've some thoughts on the topic, roughly captured [here](http://nowucca.com/technology/2011/04/20/software-engineer-seeks-jobs-in-the-silicon-valley-an-experience.html)  but probably not "extracting enough privilege" to make it really accessible yet.  

Some other resources:
- at [GlassDoor](https://www.glassdoor.com/Interview/software-engineer-interview-questions-SRCH_KO0,17.htm)
- at [developer.com](http://www.developer.com/mgmt/three-types-of-interview-questions-software-developers-should-expect.html)
- at [tutorialspoint](http://www.tutorialspoint.com/software_engineering/software_engineering_interview_questions.htm)

**Comment by trucnguyen** [comment]
Algorithms and Whiteboard Interviewing Prep (content needs to be added to the repo) are new workshops that address thse needs
