### ISSUE TITLE
[css3] missing file write_doraemon.html

### ISSUE THREAD

**Issue by brendajin** [gdisf/teaching-materials#307]
Reference to file in `<iframe>` is not found:
file referenced: `css3/files/rounded/write_doraemon.html`
in `css3/index.html` line `1033`

The following files are also missing:

```
css3/files/rounded/write_doraemon.html
css3/css/page-bg.jpg
css3/files/02_uiselectors.html
css3/files/04_firstlastonly.html
css3/css/page-bg.jpg
css3/files/009_bubble.html
```

**Comment by pamelafox** [comment]
Fixed in http://www.teaching-materials.org/css3/properties.html
