### ISSUE TITLE
[jsmvc] Remove backbone.js examples and exercises

### ISSUE THREAD

**Issue by verythorough** [gdisf/teaching-materials#313]
The `/jsmvc` directory contains a demo, exercise, and exercise solution using backbone.js, but these are no longer referenced in the slides, presumably because the content was replaced with the Backbone workshop.  I suggest we remove these files:
- [ ] `/jsmvc/demo/bookshelf_backbone.html`
- [ ] `/jsmvc/exercise_backbone.html`
- [ ] `/jsmvc/exercise_backbone_solution.html`

**Comment by binerys** [comment]
@binerys on it :)
