### ISSUE TITLE
[ajax] File that possibly needs to be moved to ../common?

### ISSUE THREAD

**Issue by selva-oscura** [gdisf/teaching-materials#322]
ajax/exercise_ajax.html (line 18) includes a link to ../resources/testinglocally.html which contains the explanation of how to use python to serve files, so that the browsers won't reject accessing the .json files locally.
Should the ../resources/testinglocally.html file be moved to the ../common directory?
(If so, the link will also need to be updated.)

**Comment by trucnguyen** [comment]
common is used for external libraries
