### ISSUE TITLE
Create JS exercise based on name game

### ISSUE THREAD

**Issue by pamelafox** [gdisf/teaching-materials#33]
http://en.m.wikipedia.org/wiki/The_Name_Game

"A verse can be created for any name, wi

thX as the name and Y as the name without the first consonant sound (if it begins with a consonant), as follows:

```
(X), (X), bo-b (Y)
Banana-fana fo-f (Y)
Fee-Fi-mo-m (Y)
(X)!
```

If the name starts with a vowel or vowel sound, the "b" "f" or "m" is inserted in front of the name."

**Comment by brendajin** [comment]
@pamelafox which workshop should this go in?

**Comment by pamelafox** [comment]
Hm. I'm not sure if I envisioned it as a standalone exercise for something like a PairUp or as an exercise for JS 101.  It's a little advanced for JS 101, it'd involve various string methods.  It could be a homework for the faster students. I'd say you can close it or ask folks at the AnnieCannons hackathon to exercise-ify it, your call.

**Comment by verythorough** [comment]
The techniques required for this are not so different from those in http://www.teaching-materials.org/javascript/exercises/strings.html, which is currently linked after in the JS101 index page under lesson 1 (which, as it turns out, is really too early, since students haven't even learned if/else construction yet).

**Comment by pamelafox** [comment]
Ah. Bit of history: that strings exercise is based off an exercise from the Google Python class, which teaches concepts in a different order. 

I think the Strings exercises might even need to be moved to Lesson 3, because it involves using methods on strings, which is basically  treating the strings as each objects. I believe there is a single slide on built-in objects - String, Date, Number, etc, but JS 101 never had time to go deeper into that or do an in-class exercise on it. 

So you could put exercises like these as Bonus Homework for Lesson 3 or drop them from 101 entirely?

**Comment by brendajin** [comment]
I think it would be good to expand on built in methods. The JS 101 was
recently taught in 2 days, so we have a bit more room to expand on some
topics.
