### ISSUE TITLE
[CSS3] Things to fix

### ISSUE THREAD

**Issue by cdersky** [gdisf/teaching-materials#341]
Selectors:
- [x] Update CSS3 history slide
- [x] Find a nice CSS selector browser compatibility chart
- [ ] Find selectors exercise made by previous TA
- [x] remove 'sucks' from sildes
- [x] remove the IE 6 and IE 7 notes from slides
- [x] link to MDN on every slide
- [x] move first two examples from slide: CSS3 Attribute Selectors to its own slide that should follow slide: 'Older attribute selectors'. The remaining examples on  slide: CSS3 Attribute Selectors and the two bottom examples from slide 'Older attribute selectors' should be one one slide to follow.
- [x] slide: Attribute Selectors Recap replace @media with a 'try it out'
- [x] add commented out examples to files/01_attr.html
- [ ] add exercise after relational selectors
- [x] add exercise after form selectors (which will cover attr and form)
- [ ] fix solution link for final exercise
- [x] add pseudo classes review slide - take from HTML/CSS class?
- [x] On UI pseudo classes slide, add input:checked { outline: 2px solid red; }
- [x] Fix link for Form UI pseudo-classes pop out

Properties:
- [x] Add flex box slides and exercise
- [x] Break logo exercise into 2, second one has them animate
- [x] Check all the exercises are functional

**Comment by pamelafox** [comment]
All done, closing this issue. I'll start a new issue for improvements I note after this delivery.
