### ISSUE TITLE
[css3-selectors] Suggestions for CSS3 Selectors Slides

### ISSUE THREAD

**Issue by pamelafox** [gdisf/teaching-materials#379]
- [ ] Add an attributes exercise. The time was tight (6:30-9) already, so some trimming would help. Suggest removing the |= ~= slide, making them a footnote if anything. While delivering, I was 1) talking over the slides, 2) showing stuff in an in-class example in JSbin, and 3) going through the "Try it out" links with them - which is why it took so much time. Probably just pick 2 out of those 3 techniques!
- [ ] Change ::before example to a more easily grokkable example, like a simple line or a symbol inserted after a link (like the Try it now links in the slides!). Keep link to bubbles cuz they're cool.

Note: It's fun to show real-world examples of the selectors on websites in the wild / websites that you've worked on. I suggest prepping a few to show for whoever teaches it next.

**Comment by pamelafox** [comment]
Note: One option for the attributes exercise could be the Form exercise, but just the first steps.

**Comment by alfasf** [comment]
got this one!
