### ISSUE TITLE
[jsmvc] This course no longer seems to work

### ISSUE THREAD

**Issue by swedishpotato** [gdisf/teaching-materials#389]
HI,

The slides for the JSMVC look great, but none of the demos or exercises here work, mainly it seems to broken links to jQuery and Bootstrap etc, which point to local host versions on teaching materials org which are now dead. Any chance this could be corrected so that this course, well, works? A pity so much hard work goes to waste if it doesn't actually work.

Cheers,

Michael

**Comment by trucnguyen** [comment]
@swedishpotato Could you be more specific about which folders are erroring out and what the issue is? [include screenshots]

**Comment by trucnguyen** [comment]
Thanks, will look into it.

Also, we have an Open Source Hack day coming up!
https://www.meetup.com/Girl-Develop-It-San-Francisco/events/241118039/

**Comment by swedishpotato** [comment]
Wow, fast! Thanks!

Slide 10 - http://www.teaching-materials.org/jsmvc/#/10 - Try It link - does not work
Slide 15 - http://www.teaching-materials.org/jsmvc/#/15 - Exercises do nothing
Slide 18 - http://www.teaching-materials.org/jsmvc/#/18 - Does nothing (displays empty bookcase)
Slide 19 - http://www.teaching-materials.org/jsmvc/#/19 - Does not work
Slide 21 -http://www.teaching-materials.org/jsmvc/#/21 - ToDo link is broken

**Comment by trucnguyen** [comment]
How about now?
