### ISSUE TITLE
[htmlcss-selfpaced] Update README.md

### ISSUE THREAD

**Issue by kellybelly** [gdisf/teaching-materials#448]
Please update `README.md` in the `/htmlcss-selfpaced/` folder.

- [ ] Find the class title + description [here](https://docs.google.com/document/d/1i3HOT1Mh03S-n3VlwAM6CWXzHlBb_V_QrowEy2jYOHY/edit?usp=sharing) (PRO-TIP: search for `htmlcss-selfpaced`).

- [ ] Remove all existing content in `README.md`.

- [ ] Add the following to `README.md`:
```
# {{ CLASS_TITLE }}
```
where `{{ CLASS_TITLE }}` is the class title found in the google doc above.

- [ ] Add the class description found in the google doc above.

- [ ] Check that bolded text, italic text, lists, links are properly formatted.

**Comment by jasminerosen** [comment]
@jasminerosen got it!

**Comment by verythorough** [comment]
Closed by #506. Thanks, @jasminerosen!
