### ISSUE TITLE
[jsreview] Update README.md

### ISSUE THREAD

**Issue by kellybelly** [gdisf/teaching-materials#459]
Please update `README.md` in the `/jsreview/` folder.

- [ ] Find the class title + description [here](https://docs.google.com/document/d/1i3HOT1Mh03S-n3VlwAM6CWXzHlBb_V_QrowEy2jYOHY/edit?usp=sharing) (PRO-TIP: search for `jsreview`).

- [ ] Remove all existing content in `README.md`.

- [ ] Add the following to `README.md`:
```
# {{ CLASS_TITLE }}
```
where `{{ CLASS_TITLE }}` is the class title found in the google doc above.

- [ ] Add the class description found in the google doc above.

- [ ] Check that bolded text, italic text, lists, links are properly formatted.

**Comment by snidelyhazel** [comment]
I'm on a spree!

**Comment by trucnguyen** [comment]
I can't keep up with reviewing! 😅

**Comment by snidelyhazel** [comment]
No worries! I just really appreciate this opportunity to practice Git. 😊

Coming from the gamedev world where I've only ever used Mercurial and Perforce, it's a bigger transition than people realize! 😅
