### ISSUE TITLE
[ajax] Update README.md

### ISSUE THREAD

**Issue by kellybelly** [gdisf/teaching-materials#466]
Please update `README.md` in the `/ajax/` folder.

- [ ] Find the class title + description [here](https://docs.google.com/document/d/1i3HOT1Mh03S-n3VlwAM6CWXzHlBb_V_QrowEy2jYOHY/edit?usp=sharing) (PRO-TIP: search for `ajax`).

- [ ] Remove all existing content in `README.md`.

- [ ] Add the following to `README.md`:
```
# {{ CLASS_TITLE }}
```
where `{{ CLASS_TITLE }}` is the class title found in the google doc above.

- [ ] Add the class description found in the google doc above.

- [ ] Check that bolded text, italic text, lists, links are properly formatted.

**Comment by juliaberk** [comment]
On it!
