### ISSUE TITLE
[cli] Add README.md

### ISSUE THREAD

**Issue by kellybelly** [gdisf/teaching-materials#470]
Please add a `README.md` file to the `/cli/` folder.

- [ ] Find the class title + description [here](https://docs.google.com/document/d/1i3HOT1Mh03S-n3VlwAM6CWXzHlBb_V_QrowEy2jYOHY/edit?usp=sharing) (PRO-TIP: search for `cli `).

- [ ] Create a new `README.md` in the `/cli/` folder.

- [ ] Add the following to `README.md`:
```
# {{ CLASS_TITLE }}
```
where `{{ CLASS_TITLE }}` is the class title found in the google doc above.

- [ ] Add the class description found in the google doc above.

- [ ] Check that bolded text, italic text, lists, links, images are properly formatted.

- [ ] In `index.html`, add the link to `README.md` to the `PROG101: Command-line` row:

```
<td><a href="https://github.com/gdisf/teaching-materials/blob/master/cli/README.md">Meetup description</a>
```

- [ ] Test the link

**Comment by alfasf** [comment]
working on this issue but cannot link image given from google docs, and the row PROG101: Command-line can't be found in index.html.

**Comment by trucnguyen** [comment]
@alfasf it's just `Class: Intro to the Command Line/Terminal` fine to leave out the image
