### ISSUE TITLE
[git] Add README.md

### ISSUE THREAD

**Issue by kellybelly** [gdisf/teaching-materials#471]
Please add a `README.md` file to the `/git/` folder.

- [ ] Find the class title + description [here](https://docs.google.com/document/d/1i3HOT1Mh03S-n3VlwAM6CWXzHlBb_V_QrowEy2jYOHY/edit?usp=sharing) (PRO-TIP: search for `git`).

- [ ] Create a new `README.md` in the `/git/` folder.

- [ ] Add the following to `README.md`:
```
# {{ CLASS_TITLE }}
```
where `{{ CLASS_TITLE }}` is the class title found in the google doc above.

- [ ] Add the class description found in the google doc above.

- [ ] Check that bolded text, italic text, lists, links are properly formatted.

- [ ] In `index.html`, add the link to `README.md` to the `PROG102: Intro to Git & GitHub` row:

```
<td><a href="https://github.com/gdisf/teaching-materials/tree/master/git/README.md">Meetup description</a>
```

- [ ] Test the link

**Comment by paolinAGE** [comment]
@paolinAGE got it!
