### ISSUE TITLE
[web accessibility] Fix typos on Slide 11

### ISSUE THREAD

**Issue by mejarc** [gdisf/teaching-materials#478]
* "Challange" should be "Challenge"
* "Assuptions" should be "Assumptions"

https://www.teaching-materials.org/accessibility/#/11

In this file:
/accessibility/index.html

Lines 230-239

**Comment by verythorough** [comment]
Thanks so much for identifying this, @mejarc! I'm tagging for our curriculum hack night tonight. Would you like to tackle this yourself?

**Comment by mejarc** [comment]
@verythorough, I'll be glad to work on it today (1-Aug-2017). I don't see the means for me to claim the issue.

**Comment by verythorough** [comment]
Thanks, @mejarc! If you decide to take on any other issues, you can claim them by making a comment.
