### ISSUE TITLE
[Algorithms] Slide 19 Weird spacing

### ISSUE THREAD

**Issue by hyendler** [gdisf/teaching-materials#479]
<img width="1048" alt="screen shot 2017-07-31 at 5 26 40 pm" src="https://user-images.githubusercontent.com/13226643/28804018-7d9107de-7615-11e7-8fb0-6366ae959672.png">
Weird spacing issue, need newline break

**Comment by coldzonemt** [comment]
@coldzonemt I've got it!

**Comment by standardhuman** [comment]
@standardhuman No, I've got it!
