### ISSUE TITLE
[CSS3] Fix step 1 of the selectors exercise to be background-color

### ISSUE THREAD

**Issue by pamelafox** [gdisf/teaching-materials#48]
Cuz it's already bold!

**Comment by brendajin** [comment]
Depends on this being closed first: https://github.com/gdisf/teaching-materials/issues/197

**Comment by brendajin** [comment]
#197 is closed – this issue is ready to be addressed

**Comment by brendajin** [comment]
**File referenced**
`css3/exercise_tables.html`
