### ISSUE TITLE
[Algorithms] Making crepes example

### ISSUE THREAD

**Issue by hyendler** [gdisf/teaching-materials#481]
I would really like some sort of actual pseudocode instead of the half pseudocode/code examples in python.  Or at least in addition to.  So the slide order would be:
Making Crepes problem
Time efficient crepes, pseudocode (in pure english)
Time efficient crepes, in 'fake' python code
Space efficient crepes, pseudocode (in pure english)
Space efficient crepes, in 'fake' python code

**Comment by angeltam** [comment]
I got this
