### ISSUE TITLE
[Algorithms] Searching Algorithms

### ISSUE THREAD

**Issue by hyendler** [gdisf/teaching-materials#482]
I updated this particular curriculum to have students actually complete Binary Search, but that is way too hard as the very first algorithm for a student to ever complete.  

As such, I would like to update the Searching Algorithms section (so insert right after slide 61) an exercise where students have to write code to find the minimum of an array.  This would introduce the ideas of needing to keep track the index in an array, comparing values as you move through an array, etc, etc - essentially good scaffolding for attempting Binary Search.

We completed the lecture with 45 minutes to spare, as such, there is definitely time to add this as an exercise.

See the binary search complete example on slide 66 for a format to write the exercise, and include a slide after slide 61

**Comment by jpang** [comment]
On it!
