### ISSUE TITLE
[Git] Split into two different lectures

### ISSUE THREAD

**Issue by hyendler** [gdisf/teaching-materials#487]
Split the currently Git lecture into two different folders in the teaching-materials repo (you will need to fork and clone the repo to do this):
1) Git (slides 1 - 50 of current git lecture)
2) Github (slides 51 through 75)

This is linked to the large epic issue [485](https://github.com/gdisf/teaching-materials/issues/485)

**Comment by estoner-kt** [comment]
working on it with Sara
