### ISSUE TITLE
[Git] Adding command line review to Git lecture

### ISSUE THREAD

**Issue by hyendler** [gdisf/teaching-materials#492]
Add a few slides after the last setup slide (the one with the unicorn image) about command line.  Review what is command line, how to enter commands, how to change up and down between file structure (cd file_name or cd .. to go a directory), how to list all of the files/folders in current directory, how to create a new folder, how to create a new file.

This is part of the larger epic [485](https://github.com/gdisf/teaching-materials/issues/485)

**Comment by lakersfans81** [comment]
@lakersfans81 claimed issue.
