### ISSUE TITLE
[jsweb] syntax highlighting unreadable in some script blocks

### ISSUE THREAD

**Issue by trucnguyen** [gdisf/teaching-materials#544]
On slides, some of the javascript syntax highlighting is low contrast, wrong rules are being applied

**Comment by evilzero** [comment]
could you specify which page you are referring to and perhaps a link?

**Comment by trucnguyen** [comment]
The slides on jsweb - /jsweb/

Believe the css is was messed up on the <pre><code> blocks 

Example:
https://www.teaching-materials.org/jsweb/slides/dom#/12

But it looks okay now
