### ISSUE TITLE
The Puppy Age Calculator Exercise error

### ISSUE THREAD

**Issue by 4m3r** [gdisf/teaching-materials#571]
function calculateDogAge(age) {
    var dogYears = 7 * age;
    console.log("Your doggie is " + dogYears + " years old in dog years!"); 
    
}

// This is solution on your site
calculateAge(1);
calculateAge(0.5);
calculateAge(12); 
------------------------------------------
calculateDogAge(1);
calculateDogAge(0.5);
calculateDogAge(12);

**Comment by trucnguyen** [comment]
We finally got this - thanks @4m3r for reporting and @carlymichele for fixing
