### ISSUE TITLE
[github-web] Fix broken link and typo

### ISSUE THREAD

**Issue by marbleindex** [gdisf/teaching-materials#582]
Broken link on *Finding more projects* slide, specifically the "*First-Timers' Guide*" link.

The link is missing the `href` attribute. It should point here: 

https://github.com/the-ethan-hunt/first-timers-guide

There is also a typo on the same slide "...variety of tech-realted topics."

teaching-materials/github-web/index.html

**Comment by snidelyhazel** [comment]
I'm on it!
