### ISSUE TITLE
[HTML/CSS] Various suggestions for HTML Basics

### ISSUE THREAD

**Issue by pamelafox** [gdisf/teaching-materials#59]
Porting over from the site.
- On the text editors slide, make sure to actually demonstrate saving a file and opening it on the desktop vs. in Cloud9, as that's a source of confusion during the exercise.
- Reiterate that the title element goes in the  head and is not rendered on the page (this seems a matter of great confusion for newbies).
- Consider talking about the HTML as a tree structure (DOM).
- Consider downloading a screen reader and having them hear a page read aloud, so that they understand the need for accessible HTML.
- Make the HTML history slide more concise (less text-y). Clarify what was wrong with IETF's standard (why W3C was needed).
- Consider explaining <code>meta charset</code> and encoding.
- Talk about project folder structure (index.html, css folder, images folder, etc)

**Comment by brendajin** [comment]
- [ ] Reiterate that the title element goes in the head and is not rendered on the page (this seems a matter of great confusion for newbies).
- [ ] Consider talking about the HTML as a tree structure (DOM).
- [ ] Make the HTML history slide more concise (less text-y). Clarify what was wrong with IETF's standard (why W3C was needed).
- [ ] Consider explaining meta charset and encoding.

In reference to larger portfolio/gallery project:
- [ ] Talk about project folder structure (index.html, css folder, images folder, etc)

**Comment by pamelafox** [comment]
The new slides cover those points, so I think this can be closed.
