### ISSUE TITLE
TECH101: What is the Web? Meetup description URL is broken

### ISSUE THREAD

**Issue by voiceofrae** [gdisf/teaching-materials#602]
The current URL on teaching-materials.org is: https://github.com/gdisf/teaching-materials/blob/master/tech101/README.md which leads to a 404.

Based on what's in https://github.com/gdisf/teaching-materials/tree/master/tech101 it seems like this class meetup description was never created. 

My chapter is interested in teaching it - if it hasn't been taught yet, I can create the first Meetup description and then add it to Github to resolve this issue. Otherwise, if it was taught in the past, whoever taught it can add the meetup description.

**Comment by trucnguyen** [comment]
@voiceofrae It exists but the path is broken because the file name is wrong (should be uppercase).
https://github.com/gdisf/teaching-materials/blob/master/tech101/readme.md

**Comment by CrystalFaith** [comment]
I will fix this!

**Comment by trucnguyen** [comment]
Could you also rename it README.md (capital) and fix the links? Thanks!
