### ISSUE TITLE
[CSS Tools] Various suggestions

### ISSUE THREAD

**Issue by pamelafox** [gdisf/teaching-materials#62]
- [ ] Add link to Chrome Canary and FF Alpha
- [ ] Add link to https://developer.chrome.com/devtools/docs/device-mode on resolution testing slide
- [ ] Show <link rel="stylesheet" href="normalize.css" type="text/css"> for normalize slide
- [x] Upgrade slides and exercise to Bootstrap 3.
- [ ] Make in-class examples for things like Reset, Grids, Bootstrap, to make it easier to explain them.
- [x] Show BuiltWithBootstrap, explain Bootstrap-itis and the pros/cons of using a framework.
- [ ] Audit all the links

**Comment by jessiewuwu** [comment]
Hey @trucnguyen! Can you confirm that most of these are pretty much done:
- slides and exercises are updated to Bootstrap 3
- links are all working

For our new summer package workshop series, Bootstrap will have its own workshop so no need for the Bootstrap suggestions listed in this issue.

**Comment by trucnguyen** [comment]
@jessiewuwu 

Yes, I actually updated to Bootstrap 4 Alpha
Mary Ann and I ended up showing examples with the inspector offline too
