### ISSUE TITLE
JS301b: More jQuery: An error in page 8 - excercise's sollution has an error

### ISSUE THREAD

**Issue by Advonet** [gdisf/teaching-materials#639]
"linkUrl" variable is a local variable of "thumbnailify"  function.
The function "thumbnailCallback" is defined on global  scope.
Thus, there is no access to "linkUrl" within "thumbnailCallback" function.
We can access it by using e.currentTarget.

**Comment by AnutaK** [comment]
Hi @Advonet, can you please assign me to this issue? I'd like to start working on it. Thank you!

**Comment by trucnguyen** [comment]
@AnutaK Go for it
