### ISSUE TITLE
Move to deprecated folder results in 404s 

### ISSUE THREAD

**Issue by pamelafox** [gdisf/teaching-materials#640]
I reference the teaching materials URLs from various places on Khan Academy and am now needing to update them, as old slides got moved into the deprecated folder and the old links are now 404s.

I am updating all the links now, but that still means many old emails for students will 404, plus any other references to the links online. As a general rule, it's nice if links can stay forever, or at least redirect (something which isn't so easy/possible with Github). 

I am mostly posting this issue to confirm that the old URLs are now going to stay in /deprecated/, since I'm updating them now and don't want them to start 404ing again soon. 
Thanks!

**Comment by trucnguyen** [comment]
Yes, we'll keep them around!

**Comment by pamelafox** [comment]
Okay, thanks for confirming!
