### ISSUE TITLE
[CSS3] Various suggestions

### ISSUE THREAD

**Issue by pamelafox** [gdisf/teaching-materials#74]
CSS3 Attribute selectors
- Should we have examples on the slides?

Exercise:
- doesn't work in Chrome
- Just go through it, since we have our own exercise

UI pseudo-classes:
- maybe show HTML for checked/default

**Comment by brendajin** [comment]
Depends on https://github.com/gdisf/teaching-materials/issues/197

**Comment by pamelafox** [comment]
Addressed in latest revision
